<?php

namespace iahm\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends EntityRepository
{
    public function findDonations(Family $entity)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT e
                FROM iahmContactBundle:Family e
                LEFT JOIN e.donations d
                WHERE e.id = :entity_id'
            )->setParameters(
                array(
                    'entity_id' => $entity->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findGroups(Family $entity)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT e, g
                FROM iahmContactBundle:Family e
                LEFT JOIN e.units g
                WHERE e.id = :entity_id'
            )->setParameters(
                array(
                    'entity_id' => $entity->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
