<?php

namespace iahm\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonTypeRepository extends EntityRepository
{

    public function findOneByRelation(Family $entity, Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT pt
                FROM iahmContactBundle:PersonType pt
                JOIN pt.family e
                JOIN pt.person p
                WHERE p.id = :contact_id
                AND e.id = :entity_id'
            )->setParameters(
                array(
                    'entity_id' => $entity->getId(),
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
