<?php

namespace iahm\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{

    public function findEvents(Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p
                FROM iahmContactBundle:Person p
                LEFT JOIN p.events e
                WHERE p.id = :contact_id
                ORDER BY e.start ASC'
            )->setParameters(
                array(
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findGroups(Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p
                FROM iahmContactBundle:Person p
                LEFT JOIN p.memberOfs m
                LEFT JOIN p.leaderOfs l
                WHERE p.id = :contact_id'
            )->setParameters(
                array(
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findMembers(Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p
                FROM iahmContactBundle:Person p
                LEFT JOIN p.memberOfs m
                WHERE p.id = :contact_id'
            )->setParameters(
                array(
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findLeaders(Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p
                FROM iahmContactBundle:Person p
                LEFT JOIN p.leaderOfs l
                WHERE p.id = :contact_id'
            )->setParameters(
                array(
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findDonations(Person $contact)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p
                FROM iahmContactBundle:Person p
                LEFT JOIN p.donations d
                WHERE p.id = :contact_id'
            )->setParameters(
                array(
                    'contact_id' => $contact->getId()
                )
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
